### ISSUE TITLE
Website Download Link for Windows/Linux is invalid

### ISSUE THREAD

**Issue by Braunson** [hugeinc/styleguide#14]
Hey there,

There wasn't anywhere to edit the site (on GH) nor a contact section but the Windows-Linux link is invalid and return 404 Not Found.

Perhaps this is what it should be. 
`https://github.com/hugeinc/styleguide/archive/release/windows-linux.zip`

**Comment by caiovaccaro** [comment]
Hi @Braunson , thanks a lot!

The branching model was updated and the website wasn't. Just did that now.

**Comment by caiovaccaro** [comment]
The source of the site will be public in a separate repo very soon, thanks again for your help and interest!

**Comment by Braunson** [comment]
:+1:
