### ISSUE TITLE
Port conflict for users with php-fpm installed

### ISSUE THREAD

**Issue by elzii** [hugeinc/styleguide#15]
OSX

After installing the app without issue, Chrome opens `localhost:9000` and I get a "No data received - ERR_EMPTY_RESPONSE".

![ERR_EMPTY_RESPONSE](http://i.imgur.com/HTWuq8T.png)

I assume there may be a port conflict so I ran `lsof -n -i4TCP:9000 | grep LISTEN` and got

```
php-fpm  405 USERNAME    6u  IPv4 0xeed2746b5d24b21      0t0  TCP 127.0.0.1:cslistener (LISTEN)
php-fpm  546 USERNAME    0u  IPv4 0xeed2746b5d24b21      0t0  TCP 127.0.0.1:cslistener (LISTEN)
php-fpm  548 USERNAME    0u  IPv4 0xeed2746b5d24b21      0t0  TCP 127.0.0.1:cslistener (LISTEN)
php-fpm  551 USERNAME    0u  IPv4 0xeed2746b5d24b21      0t0  TCP 127.0.0.1:cslistener (LISTEN)
php-fpm 2369 USERNAME    0u  IPv4 0xeed2746b5d24b21      0t0  TCP 127.0.0.1:cslistener (LISTEN)
```

Rather than mess with my php install I went into `watch.js` and changed the `PORT` variable, after which all went well.

Perhaps allow a command line parameter to pass in a port manually, for users that may be affected by this, and add to the Known Issues?

Cheers,

A

**Comment by caiovaccaro** [comment]
Hey @elzii , good catch.

Thanks for this, I will do a couple of things:
- Add this case to the Known issue section
- Document on how to change the port
- Add a command line option to do it
- Change the port number, since it is also the default harp.js port

Thanks a lot for this!

**Comment by pschultz** [comment]
Please honor the `PORT` environment variable as well.

**Comment by caiovaccaro** [comment]
Will do that. Thanks again!
