### ISSUE TITLE
Pretty HTML output

### ISSUE THREAD

**Issue by KrisOlszewski** [hugeinc/styleguide#23]
Hi there, would it be possible to pass an option to Harp to not minify Jade output? It makes it difficult to read Prism code. See here: http://hugeinc.github.io/styleguide/demo/#!forms

**Comment by caiovaccaro** [comment]
Hey @KrisOlszewski ! Thank you for pointing that out.

Actually it is not possible to do it directly though Harp, as stated in this issue: https://github.com/sintaxi/harp/issues/169

But it is possible to add a step in the compilation stage, where the code would be "prettified".

**Comment by caiovaccaro** [comment]
I've just renamed your issue to the feature name. It will be released with the 2.0.4 version!

**Comment by KrisOlszewski** [comment]
Sounds great, thank you!
