### ISSUE TITLE
Represent variables in styleguide

### ISSUE THREAD

**Issue by CoralSilver** [hugeinc/styleguide#25]
Is there any way to represent sass variables in the styleguide? In the demo, for example, it shows colors by adding a class to the div which adds a background-color.  Could this be done in some way with a color variable?

**Comment by caiovaccaro** [comment]
Hi @CoralSilver ,

Yes it is possible, but right now just with explicit declaration of dependencies. What this means exactly? Better shown in an example:

In the same way that in modern javascript applications you have imports at the top of every file and you have to import every dependent part, even what you need repeatedly in several files: 
```javascript
import config from 'setup'
import $ from 'jquery'
import bootstrap-datepicker from 'bootstrap'
```

At this point in the Styleguide, you have to explicitly import a global file in all your sass files:

```css
// assets/styles/_global.sass
$theNewBlack: #333
```
```css
// modules/2_colors/colors.sass
@import "../../assets/styles/_global.sass"

p
  color: $theNewBlack
```

We are considering living an option for the user to choose if he wants to load the files himself (through a main.sass file, for example) or if the Styleguide should load them file by file (as it is today). The same will apply for Javascript and module loaders.

**Comment by CoralSilver** [comment]
Thanks for the quick reply @caiovaccaro.  I guess I meant more how would ```$theNewBlack``` be represented to the user as an available variable, since HTML, but no sass code is shown in the styleguide?  For instance ```.bg-blue``` shows up over the background color in the demo. It would be cool if that could be the variable name instead, maybe also with the hex code shown.

Or is the idea behind the styleguide more that it would only be used to mark up pages and is not meant as a reference for writing new styles?

**Comment by caiovaccaro** [comment]
Hey,

I see what you mean. Actually it is completely flexible. So yes it is possible, but because of the Styleguide separation of concerns, right now you have to add any content information you want into the .json file.

So if you add something like this:
```
"colors": [
  {
    "className": "bg-magenta",
    "variable": "$magenta",
    "hex": "#000000"
  },
```

You can use that information freely in the .jade file:
```jade
div(class="color #{color.className}")
  p .#{color.variable}
```
Or:
```jade
div(class="color #{color.className}")
  p .#{color.variable}
  p .#{color.hex}
```

Or anything you want, actually. You can then style that inside the .sass file, perhaps prefixing it with the #colors id since each module has a container with the module id.

**Comment by caiovaccaro** [comment]
Does that makes sense to you @CoralSilver ?

**Comment by CoralSilver** [comment]
Yes, thanks @caiovaccaro.
