### ISSUE TITLE
If harp is not installed, it does not raise any errors

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [hugeinc/styleguide#32]
It would be nice to raise an error or something, because I just skipped that part and didn't know why it was not working :)

**Comment by caiovaccaro** [comment]
Hey @gabrielpugliese-luizalabs ! By skipped, what do you mean exactly? You have used the Start.app or the manual installation process?

Thanks!

**Comment by gabrielpugliese-luizalabs** [comment]
It's the manual process. I haven't noticed that there is an Start.app command (haven't found it yet - where is it located?)

**Comment by caiovaccaro** [comment]
What is your operating system, windows?

**Comment by gabrielpugliese-luizalabs** [comment]
Ubuntu 14.04

**Comment by caiovaccaro** [comment]
Ok! Nice, can you just write your steps so I can reproduce?

Something like:

- I installed this..
- And then did this command..

Etc. And I will add a error message for missing dependencies when starting the server.

**Comment by gabrielpugliese-luizalabs** [comment]
Ok

1. I've downloaded the bundle and unzipped
2. `cd styleguide/structure/_node-files && npm install`
3. `node watch.js`

The progress is 100% but nothing is being served because harpjs is not installed.

**Comment by gabrielpugliese-luizalabs** [comment]
I would add a command before 2. in the steps like: `npm install -g harp` and also check if harp is installed on the startup of `watch.js`

**Comment by caiovaccaro** [comment]
Perfect, I'll do that and it will be release on version 2.0.5.

Thank you!

**Comment by gabrielpugliese-luizalabs** [comment]
:rocket:

**Comment by caiovaccaro** [comment]
Closed on **develop**, soon to be merged.

https://github.com/hugeinc/styleguide/blob/develop/styleguide/structure/_node-files/watch.js
