### ISSUE TITLE
Osx El capitan - Progress stuck at 94%

### ISSUE THREAD

**Issue by laurent-d** [hugeinc/styleguide#34]
Hello, it seem not working on last beta developper of Os El capitan : 

![huge-style](https://cloud.githubusercontent.com/assets/6553086/9292555/f30246a6-4401-11e5-8da2-0de8f090107c.gif)

If you need my complete logs don't hesitate and thanks for your work :)

**Comment by caiovaccaro** [comment]
Hi! Yes I will need the complete log, please.

Thanks!

**Comment by laurent-d** [comment]
Voila the complete log

Styleguide. Welcome!
PROGRESS:50
/Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources/script: line 28: .bashrc: No such file or directory

Checking dependencies...


> node-sass@3.0.0-beta.5 install /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.0.0-beta.5 postinstall /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/harp/bin/harp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/harp/bin/harp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "harp" "-g"
npm ERR! cwd /Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/harp/bin/harp
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR! not ok code 0
npm ERR! Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/html-beautify.js'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/html-beautify.js']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/js-beautify/js/bin/html-beautify.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "js-beautify" "-g"
npm ERR! cwd /Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/js-beautify/js/bin/html-beautify.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/html-beautify.js'
npm ERR! not ok code 0
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
PROGRESS:80

Let's start this thing...
Starting Server on port 9241..
PROGRESS:94

I have already entered the command that i found in readme file.

Thanks for the support

**Comment by caiovaccaro** [comment]
Okay! Please open the Terminal, go to the Styleguide folder and execute the following commands:

```
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) /usr/local/lib/node_modules
rm .install.lock
```

And run the Start.app again. Let me know what happens after, @laurent-d .

**Comment by laurent-d** [comment]
No differences : 

Styleguide. Welcome!
PROGRESS:0
PROGRESS:50
/Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources/script: line 28: .bashrc: No such file or directory

Checking dependencies...


> node-sass@3.0.0-beta.5 install /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.0.0-beta.5 postinstall /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/harp/bin/harp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/harp/bin/harp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "harp" "-g"
npm ERR! cwd /Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/harp/bin/harp
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR! not ok code 0
npm ERR! Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/js-beautify/js/bin/css-beautify.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "js-beautify" "-g"
npm ERR! cwd /Users/laurentdelacerda/Downloads/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! not ok code 0
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
PROGRESS:80

Let's start this thing...
Starting Server on port 9241..
PROGRESS:94

**Comment by caiovaccaro** [comment]
What was the output when you ran these commands?

```
sudo chown -R $(whoami) ~/.npm
```
```
sudo chown -R $(whoami) /usr/local/lib/node_modules
```

**Comment by laurent-d** [comment]
Nothing, just a new line come : 

MacBook-Pro-de-Laurent:Downloads laurentdelacerda$ cd styleguide-master
MacBook-Pro-de-Laurent:styleguide-master laurentdelacerda$ sudo chown -R $(whoami) ~/.npm
MacBook-Pro-de-Laurent:styleguide-master laurentdelacerda$ sudo chown -R $(whoami) /usr/local/lib/node_modules
MacBook-Pro-de-Laurent:styleguide-master laurentdelacerda$

**Comment by caiovaccaro** [comment]
Hi @laurent-d . The [manual installation](http://hugeinc.github.io/styleguide/start.html#manual-install) with 'sudo' will solve your issue, but if you can help me to debug this in order to solve the problem it will be awesome.

Can you let me know the output for:

```
type node
type npm
type harp
```

Thanks!

**Comment by laurent-d** [comment]
Ok thanks for the trick :)
Yes i want to help you for sure :

Last login: Mon Aug 17 20:18:03 on ttys000
MacBook-Pro-de-Laurent:~ laurentdelacerda$ type node
node is /usr/local/bin/node
MacBook-Pro-de-Laurent:~ laurentdelacerda$ type npm
npm is /usr/local/bin/npm
MacBook-Pro-de-Laurent:~ laurentdelacerda$ type harp
-bash: type: harp: not found
MacBook-Pro-de-Laurent:~ laurentdelacerda$ 

If it's not what you want, tell me.

**Comment by caiovaccaro** [comment]
Great, thanks.

Tell me what happens:

```
npm config get prefix
```

And also try to enter the npm node_modules folder to see if it exists:
```
cd /usr/local/lib/node_modules
ls
```

Thanks again.

**Comment by laurent-d** [comment]
Here you are :

MacBook-Pro-de-Laurent:~ laurentdelacerda$ npm config get prefix
/usr/local
MacBook-Pro-de-Laurent:~ laurentdelacerda$ cd /usr/local/lib/node_modules
MacBook-Pro-de-Laurent:node_modules laurentdelacerda$ ls
gulp	npm	uncss
MacBook-Pro-de-Laurent:node_modules laurentdelacerda$ 

 Hope it help

**Comment by laurent-d** [comment]
Hi @caiovaccaro,
For information, it seems  that errors are decreased with the last update of El capitan developper release: 

Styleguide. Welcome!
PROGRESS:0
PROGRESS:50
/Users/laurentdelacerda/Desktop/styleguide-master/Start.app/Contents/Resources/script: line 28: .bashrc: No such file or directory

Checking dependencies...


> node-sass@3.0.0-beta.5 install /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.0.0-beta.5 postinstall /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
npm ERR! Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/harp/bin/harp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/harp/bin/harp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "harp" "-g"
npm ERR! cwd /Users/laurentdelacerda/Desktop/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/harp/bin/harp
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/harp/bin/harp'
npm ERR! not ok code 0
npm ERR! Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/js-beautify/js/bin/css-beautify.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "js-beautify" "-g"
npm ERR! cwd /Users/laurentdelacerda/Desktop/styleguide-master/Start.app/Contents/Resources
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path ../lib/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! not ok code 0
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data

> ws@0.4.20 install /Users/laurentdelacerda/Desktop/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/node_modules/websocket.io/node_modules/ws
> node install.js

[34m[ws v0.4.20][39m[32m Attempting to compile blazing fast native extensions.[39m
[34m[ws v0.4.20][39m[32m Native extension compilation successful![39m
blue-tape@0.1.10 node_modules/blue-tape

watch@0.14.0 node_modules/watch
├── minimist@1.1.3
└── exec-sh@0.2.0 (merge@1.2.0)

tape@4.2.0 node_modules/tape
├── inherits@2.0.1
├── defined@0.0.0
├── has@1.0.1
├── resumer@0.0.0
├── deep-equal@1.0.0
├── function-bind@1.0.2
├── through@2.3.8
├── object-inspect@1.0.2
└── glob@5.0.14 (path-is-absolute@1.0.0, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)

request@2.61.0 node_modules/request
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.4
├── tunnel-agent@0.4.1
├── oauth-sign@0.8.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.3
├── qs@4.0.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── form-data@1.0.0-rc3 (async@1.4.2)
├── mime-types@2.1.4 (mime-db@1.16.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.2)
├── tough-cookie@2.0.0
├── hawk@3.1.0 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, bluebird@2.9.34, is-my-json-valid@2.12.1)

nightwatch@0.7.11 node_modules/nightwatch
├── mkpath@0.1.0
├── q@1.4.1
├── ejs@0.8.8
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── chai-nightwatch@0.1.1 (assertion-error@1.0.0, deep-eql@0.1.3)

livereload@0.3.7 node_modules/livereload
├── opts@1.2.2
└── websocket.io@0.2.1 (debug@2.2.0, ws@0.4.20)
PROGRESS:80

Let's start this thing...
Starting Server on port 9241..
PROGRESS:94

Kind regards

**Comment by caiovaccaro** [comment]
Interesting!

Were you able to make it work with the manual install process?

**Comment by laurent-d** [comment]
Not working even with manual install

MacBook-Pro-de-Laurent:_node-files laurentdelacerda$ npm install
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
MacBook-Pro-de-Laurent:_node-files laurentdelacerda$

acBook-Pro-de-Laurent:styleguide-master laurentdelacerda$ cd styleguide/structure/_node-files && node watch.js
Starting Server on port 9241..
PROGRESS:94

Sorry about all that issues

**Comment by caiovaccaro** [comment]
Hey, no problem!

Have you done all steps of the manual install? Since you already have Node, what is left is:

```
sudo npm install harp -g
cd styleguide/structure/_node-files && npm install
node watch.js
```

**Comment by laurent-d** [comment]
That's work :) perfect.
I hope all this issue can improve for a new version

Thanks

**Comment by caiovaccaro** [comment]
Thank you for the patience @laurent-d !

**Comment by kiriaze** [comment]
Same issue - OSX 10.10.5. Was working fine with Start.app, tried running it today and it hangs at same spot. Tried methods above, but to no avail - running node watch.js results in same hang with progress stuck at 94.
