### ISSUE TITLE
The StyleguideIndex object is polluting the global/window object

### ISSUE THREAD

**Issue by davegomez** [hugeinc/styleguide#36]
On the current way the `StyleguideIndex` object is being implemented, it is polluting the `global/window` object exposing all the properties and methods, creating security holes in the application. 

The object shouldn't be globally accessible unless you want any other script to use it in some way.

**Comment by caiovaccaro** [comment]
Hi @davegomez !

Yes. Previously StyleguideIndex and StyleguideIframe called each other methods but that was dropped. Even in that case the best would be to use a module loader/definition of some sort.

In any case, there must be some testing (both manual and running the current written tests) if such change is implemented (as an IIFE for example).

Definetely important, thanks again!

**Comment by davegomez** [comment]
Let me see if I can make a successful refactor of this module.

**Comment by davegomez** [comment]
@caiovaccaro I notice you are using the `FRONT_END_TEST` constant only for testing purposes, or there is any other use of this constant?

How important is to keep this constant in the project?

**Comment by caiovaccaro** [comment]
Hi @davegomez , yes it is only for testing purposes.

I'm open to suggestions, if you want to take a look, see the travis.yml file. It should be all you need to have the tests running.

I need to be able to run the tests on Travis CI. Thanks again for your interest!

**Comment by caiovaccaro** [comment]
@davegomez , any updates on this?

Thanks!!

**Comment by davegomez** [comment]
Just getting back from vacation @caiovaccaro, let me check again the project and see how can I work on this topic.

**Comment by caiovaccaro** [comment]
Awesome @davegomez

**Comment by caiovaccaro** [comment]
Tagged for 3.0 :)

**Comment by caiovaccaro** [comment]
Will be addressed in 3.0.
