### ISSUE TITLE
LiveReload Issue

### ISSUE THREAD

**Issue by personafour** [hugeinc/styleguide#42]
OS: Windows 7
Browser: Google Chrome 44.0.2403.157 m
Error: 
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
(anonymous function) @ (index):1

Description:
Just downloaded & installed project and tried to do any changes.
![image](https://cloud.githubusercontent.com/assets/3624191/9604544/039c26aa-50c1-11e5-8d96-f4c6bb7d3822.png)

Actually, it doesn't work only if I downlodad project from GitHub. If I'm gettin project from site I have problems with *.scss compiling.

**Comment by personafour** [comment]
Also, when I start Harp server via "node watch.js" it does not open server page in browser.

**Comment by personafour** [comment]
Well, now I use installation from site and fix from this [issue](https://github.com/hugeinc/styleguide/issues/8) and it works fine. But GitHub version still has same problem.

**Comment by caiovaccaro** [comment]
Hi @personafour ! Thanks for collaborating. Can you tell me which link have you clicked to download both versions?

**Comment by personafour** [comment]
Of course. I downloaded *.zip for Windows [here](http://hugeinc.github.io/styleguide/download.html).
GitHub version I cloned from repo with "git clone https://github.com/hugeinc/styleguide.git".

**Comment by caiovaccaro** [comment]
Thank you. I will update some things and let you know. If you could test it again then it would be great.

**Comment by personafour** [comment]
Of course. No problem.

**Comment by caiovaccaro** [comment]
@personafour , can you try again through the .zip from the site? Thanks!

**Comment by personafour** [comment]
@caiovaccaro, works fine. Without SCSS compiling errors.

**Comment by personafour** [comment]
Command Line runned in Administrator mode, if it's necessary.

**Comment by caiovaccaro** [comment]
Perfect, thanks!

**Comment by personafour** [comment]
But... Problem with livereload still there...
![image](https://cloud.githubusercontent.com/assets/3624191/9652212/e439c79c-5221-11e5-8468-ba1768f57215.png)

**Comment by caiovaccaro** [comment]
Alright, reopening issue! :)

**Comment by caiovaccaro** [comment]
@personafour , does this error causes any side effect? Or it is just that the livereload doesn't work?

Thanks.

**Comment by personafour** [comment]
@caiovaccaro just livereload doesn't work. If I reload page manually - changes will be show

**Comment by Nipher** [comment]
Seems like livereload server is running on a diffrent port: ```8374```
but when livereload injects the script tag on the page, he is using the port ```35729```

livereload server is running on the port ```8374``` because of this line:
#L13 (https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_node-files/modules/livereloader.js#L13)
causing this issue...

If I remove the #L13, livereload works.

I'm looking for why livereload didn't inject the script with the right port....

**Comment by Nipher** [comment]
Fixed! #58 
Hey @personafour, can you download and try again?
Thanks!

**Comment by caiovaccaro** [comment]
@personafour , can you do one more test?

**Comment by mrchaarlie** [comment]
Fwiw, I've had the same problem as @personafour, and it seems to be fixed after #58.

**Comment by Nipher** [comment]
Nice! \o/
Thanks @mrchaarlie! :grin:
