### ISSUE TITLE
Sync all branches with master for latest version bump (2.0.5)

### ISSUE THREAD

**Issue by caiovaccaro** [hugeinc/styleguide#49]

**Comment by caiovaccaro** [comment]
2 more to go: example/react and release/windows-linux

**Comment by Nipher** [comment]
Sure, will do :+1: 
when merging master into release/windows-linux I get a lot of conflicts.

**Comment by Nipher** [comment]
done :+1:

**Comment by caiovaccaro** [comment]
You rock!
