### ISSUE TITLE
Missing .editorconfig

### ISSUE THREAD

**Issue by Nipher** [hugeinc/styleguide#51]
Shouldn't we create an .editorconfig file?

**Comment by davegomez** [comment]
We definitely should.

**Comment by caiovaccaro** [comment]
Go ahead @Nipher -san!

**Comment by Nipher** [comment]
I'm looking at some files, and I'm seeing a lot of different settings...
like, some of them are:
```
indent_style = tab
indent_size = 4
```
Others are:
```
indent_style = space
indent_size = 2
```
and even:
```
indent_style = tab
indent_size = 8
```

So I'm confuse about what settings to use, but I like the second one, for all files...
and of course, others settings as well:
 ```
# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Set default charset
[*]
charset = utf-8

# Indentation
[*]
indent_style = space
indent_size = 2
```

What do you guys think?

**Comment by caiovaccaro** [comment]
I like, go ahead with your configs.

What do you think @davegomez ?

**Comment by Nipher** [comment]
I've added this line too:
`max_line_length = 80`
and theses for .md file
```
[*.md]
max_line_length = 0
trim_trailing_whitespace = false
```
