### ISSUE TITLE
Wrong windows-linux download link

### ISSUE THREAD

**Issue by Nipher** [hugeinc/styleguide#54]
On the page http://hugeinc.github.io/styleguide/start.html
the link for downloading the windows / linux version seems wrong.
Link: https://github.com/hugeinc/styleguide/archive/windows-linux.zip

On the page http://hugeinc.github.io/styleguide/download.html it is **correct**
**Correct** Link: https://github.com/hugeinc/styleguide/archive/release/windows-linux.zip

There was an issue like this before ( ref #14 ), but you guys missed the Getting Started page.

I would like to fix it, but I'm not finding the code.... :weary:

**Comment by Nipher** [comment]
I've found it! :grin:

**Comment by Nipher** [comment]
Figure out that the website is on another repository
so I opened a pull request there:
https://github.com/hugeinc/styleguide-website/pull/19

**Comment by caiovaccaro** [comment]
PR merged, link replaced.
