### ISSUE TITLE
Determine all features dependent on Harp 

### ISSUE THREAD

**Issue by caiovaccaro** [hugeinc/styleguide#65]

**Comment by caiovaccaro** [comment]
**Features that uses Harp:**
  1. Separate content from HTML through _data.json. Can be done using task runners.
  2. Usage of Jade or similar. Can be done with Express and others.
  3. Usage of environment vars on templates. Can be done with Express and others.
  4. Read directory trees and file structures in a JSON object. Can **not** be easily done without Harp or trying to reuse Harp's dependencies to create similar behavior.  
  
  4.1 Build menu based on the folder structure.
  4.2 Build modules list based on the folder and file structure.

**Features that does not depend on Harp:**
  1. Write date of last modification
  2. Compile all stylesheets in one file
  3. Compile all javascripts in one file
  4. Livereload
  5. Server
  6. Tests

**Problems of using Harp:**
  1. Having to stick with specific versions of pre-compilers like Sass, which limits the use of latest features

**Benefits of using Harp:**
  1. It is fast
  2. The user don't have to wait for file compilation tasks
  3. Provides a good MV separation by using data layer 
  4. Provides a JSON object of the directory tree which is useful for automation tasks
  5. It is based on Node and can be used as an Express middleware which means it can be extended

**Comment by caiovaccaro** [comment]
@davegomez and @Nipher please review.

**Comment by caiovaccaro** [comment]
@bella-silveira please review.

**Comment by davegomez** [comment]
I think we can easily achieve all of harp's features the style guide is using making it even easier for the final user. Let me dig deeper in harp this weekend to learn more about what it does.

**Comment by Nipher** [comment]
> **Features that uses Harp:**
> 1. Separate content from HTML through _data.json. Can be done using task runners.
> 2. Usage of Jade or similar. Can be done with Express and others.
> 3. Usage of environment vars on templates. Can be done with Express and others 

I Agree. :+1: 
> 4 - Read directory trees and file structures in a JSON object. Can not be easily done without Harp or trying to reuse Harp's dependencies to create similar behavior.

>4.1. Build menu based on the folder structure.
>4.2. Build modules list based on the folder and file structure.

I've some doubts about how `public.styleguide.modules` is populated in https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_includes/modulesData.jade#L1
But I think it is done by harp... right? as you mentioned above:
> Read directory trees and file structures in a JSON object. 

I'm not really sure what this means, does harp reads the directory tree and transform that data to json for rendering the views?


---
>**Features that does not depend on Harp:**

Ok, agree. :+1: 

---

>**Problems of using Harp:**
  1. Having to stick with specific versions of pre-compilers like Sass, which limits the use of latest features

This is sad... we could create express middlewares for compiling the styles, using the original CSS Preprocessors compilers directly.
like: https://github.com/sass/node-sass for example

---
>**Benefits of using Harp:**
  1. It is fast

Ok, agree :+1: 

> 2. The user don't have to wait for file compilation tasks

I think that using express middlewares, using the original preprocessors compilers would have the same effect...

> 3. Provides a good MV separation by using data layer 

Hm :+1: 

> 4. Provides a JSON object of the directory tree which is useful for automation tasks

I need to have a look at this, don't know if can be easily done with some other tool

> 5. It is based on Node and can be used as an Express middleware which means it can be extended

Very cool \o/

---

### Conclusion
I don't have any objections of using harp, but we could create express middlewares for css preprocessors right? :smile:

**Comment by davegomez** [comment]
I think if we use the server only for development we don't need express/koa at all. We can use a bundler tool like webpack to do all the stuff harp does and create a build task to compile a public version of the style guide so the users can include it in their project.

But maybe I'm missing something here.

**Comment by caiovaccaro** [comment]
@Nipher Harp is based on Node, it reads the folder structure from the root and transform it in a JSON object, which is available on Jade, EJS, etc.

The difference is that Harp does not compile the files. In reality it just "compile" them in memory. The same thing can be acomplished with [terraform](https://www.npmjs.com/package/terraform) (also from Harp's developers).

@davegomez we might need a server in order to allow AJAX and maybe control routes.

**Comment by bella-silveira** [comment]
I agree with basically everything, but I don't really see harp not being
able to upgrade to other versions of precompilers as a major problem, since
we could really create express middlewares to solve this issue, as @Nipher
said himself.

2015-11-27 17:07 GMT-02:00 Caio Vaccaro <notifications@github.com>:

**Comment by caiovaccaro** [comment]
@bella-silveira then we should decide if we need Harp.

@davegomez what do you think? If we can get fast compilation of any css pre-processor and HTML template engine the user want (Harp allows this, just by changing the file extension) and read the directory tree as JSON object we are good to go.

**Comment by davegomez** [comment]
In my opinion Harp is too big for what we need.

I can't say for sure that Harp compiles all the files faster than Webpack but I know we can compile any kind of file using Webpack and its loaders just changing the file extension, we can add even more file types support.

For the JSON directory tree I think we have to make our own version or use another library.

@caiovaccaro can you lend me a Harp's JSON file with the directory structure to see how it looks please?

**Comment by caiovaccaro** [comment]
@davegomez another really important thing is that we need to **compile** the Styleguide in static HTML afterwards, because a requirement is that it can be ran locally without internet or a server.

I will post the JSON object here in a bit.

**Comment by caiovaccaro** [comment]
Here it is @davegomez. This is the output for the variable **public**, a default variable that Harp makes available. I just did JSON.stringify(public).

```
{
	"_contents": ["AUTHORS.html", "CONTRIBUTING.html", "LICENSE.html", "README.html", "index.html", "livereload.js"],
	"Compile.app": {
		"Contents": {
			"_contents": ["Info.plist"],
			"MacOS": {
				"_contents": ["Compile"]
			},
			"Resources": {
				"_contents": ["AppSettings.plist", "MainMenu.nib", "appIcon.icns", "script"]
			}
		}
	},
	"Start.app": {
		"Contents": {
			"_contents": ["Info.plist"],
			"MacOS": {
				"_contents": ["Start"]
			},
			"Resources": {
				"_contents": ["AppSettings.plist", "MainMenu.nib", "appIcon.icns", "script"]
			}
		}
	},
	"styleguide": {
		"_contents": ["styleguide.html"],
		"_data": {
			"clientName": "",
			"version": "2",
			"language": "en_US",
			"logoImage": "huge-logo.svg",
			"breakpoints": [{
				"id": "small",
				"name": "Small",
				"size": "420px"
			}, {
				"id": "medium",
				"name": "Medium",
				"size": "720px"
			}, {
				"id": "large",
				"name": "Large",
				"size": "1280px"
			}, {
				"id": "full",
				"name": "Full",
				"size": "100%"
			}],
			"translations": {
				"pt_BR": {
					"begining": "Início",
					"styleguide": "Styleguide"
				},
				"en_US": {
					"begining": "Beginning",
					"styleguide": "Styleguide"
				},
				"es_CO": {
					"begining": "Inicio",
					"styleguide": "Styleguide"
				}
			},
			"date": "2015/11/28"
		},
		"assets": {
			"fonts": {
				"Huge": {
					"_contents": ["GalaxieCopernicus-Book.eot", "GalaxieCopernicus-Book.svg", "GalaxieCopernicus-Book.woff", "GalaxieCopernicus-BookItalic.eot", "GalaxieCopernicus-BookItalic.svg", "GalaxieCopernicus-BookItalic.woff", "huge_agb_v5-webfont.eot", "huge_agb_v5-webfont.svg", "huge_agb_v5-webfont.woff", "stylesheet.css"]
				}
			},
			"images": {
				"_contents": ["huge-logo.svg", "logo_placeholder.png", "template01.svg"]
			},
			"scripts": {
				"_contents": ["styleguide.js"]
			},
			"styles": {
				"_contents": ["structure.css", "styleguide.css"]
			}
		},
		"modules": {
			"1_introduction": {
				"_contents": ["introduction.js", "introduction.css"],
				"_data": {
					"id": "introduction",
					"name": "Introduction",
					"scripts": ["introduction.js"],
					"items": ["Hello! Welcome to the Styleguide, A tool to make creating and maintaining styleguides easy.", "Please feel free to collaborate with the project <a href='http://github.com/hugeinc/styleguide'>on Github</a>. You can read the documentation <a href='http://hugeinc.github.io/styleguide/'>here</a>."],
					"order": "1"
				}
			},
			"2_colors": {
				"_contents": ["colors.css"],
				"_data": {
					"id": "colors",
					"name": "Colors",
					"items": {
						"intro": ["Huge have two main colors: Magenta and Black. Additional Blue might be found on slides or t-shirts."],
						"colors": [{
							"className": "bg-magenta"
						}, {
							"className": "bg-black"
						}, {
							"className": "bg-grey"
						}, {
							"className": "bg-blue"
						}]
					},
					"order": "2"
				}
			},
			"3_typography": {
				"_contents": ["typography.css"],
				"_data": {
					"id": "typography",
					"name": "Typography",
					"hasScript": "yes",
					"items": {
						"fonts": [{
							"heading": "1",
							"fontName": "HUGE Avant Garde Bold",
							"fontSize": "100px",
							"className": "font-huge",
							"title": "Hello."
						}, {
							"heading": "2",
							"fontName": "Galaxie Copernicus Book Italic",
							"fontSize": "80px",
							"className": "font-galaxie italic",
							"title": "Thursday"
						}, {
							"heading": "3",
							"fontName": "HUGE Avant Garde Bold",
							"fontSize": "38px",
							"className": "font-huge small-3",
							"title": "Born Hackers: Digital Kids Revisited."
						}],
						"paragraphsName": "Paragraphs",
						"paragraphs": [{
							"className": "p1",
							"text": "SEO is a marketing tactic that costs five percent of overall budget but brings in more than 20 percent of revenue for many Fortune 500 companies, and yet very few of them prioritize it. Instead, while slowly changing, too many CMOS still favor paid search, which costs 20 percent and brings in… 20 percent. In search, businesses need to shift priorities. Now."
						}, {
							"className": "p2",
							"text": "Link volume is one of the most powerful signals search engines use to rank websites. There’s a way to use links to generate better search results, but too many marketers rely on traditional (or even black hat) tactics that just don’t work anymore."
						}, {
							"className": "p3 small-3",
							"text": "Huge to be recognized at the 2014 “Made in NY” Awards for the company’s contribution to New York’s creative economy."
						}]
					},
					"order": "3"
				}
			},
			"4_buttons": {
				"_contents": ["buttons.css"],
				"_data": {
					"id": "buttons",
					"name": "Buttons",
					"hasScript": "yes",
					"items": [{
						"buttonName": "Load more",
						"className": "button black"
					}],
					"order": "4"
				}
			},
			"5_lists": {
				"_contents": ["lists.css"],
				"_data": {
					"id": "lists",
					"name": "Lists",
					"hasScript": "yes",
					"items": {
						"notOrdenated": "Unordered",
						"ordenated": "Ordered"
					},
					"order": "5"
				}
			},
			"6_forms": {
				"_contents": ["forms.css"],
				"_data": {
					"id": "forms",
					"name": "Forms",
					"hasScript": "yes",
					"items": {
						"disabled": "Disabled"
					},
					"order": "6"
				},
				"vendor": {
					"_contents": ["foundation-form.css"]
				}
			},
			"7_tables": {
				"_contents": ["tables.css"],
				"_data": {
					"id": "tables",
					"name": "Tables",
					"hasScript": "yes",
					"items": {
						"tables": [{
							"tableClass": "",
							"head": ["Offices", "Job Openings in Technology"],
							"body": [{
								"td": ["Atlanta", "6"]
							}, {
								"td": ["Brooklyn", "12"]
							}, {
								"td": ["London", "1"]
							}, {
								"td": ["Rio de Janeiro", "3"]
							}, {
								"td": ["San Francisco", "3"]
							}, {
								"td": ["Singapore", "2"]
							}, {
								"td": ["Washington DC", "2"]
							}],
							"footer": []
						}]
					},
					"order": "7"
				}
			},
			"8_templates": {
				"_contents": ["templates.css"],
				"_data": {
					"id": "templates",
					"name": "Templates",
					"hasScript": "yes",
					"items": {
						"templates": [{
							"link": "",
							"templateName": "Home",
							"thumbnailFile": "template01.svg"
						}]
					},
					"order": "8"
				}
			}
		},
		"structure": {
			"_contents": ["README.html"],
			"images": {
				"_contents": ["close.svg", "favicon.png", "h.jpg", "hamburger.svg", "huge-logo.svg", "icon_code.svg", "icon_code_white.svg", "icon_full.svg", "icon_large_up.svg", "icon_medium_up.svg", "icon_small_up.svg", "logoHuge.png"]
			},
			"scripts": {
				"_contents": ["iframe.js", "styleguide.js"],
				"vendor": {
					"_contents": ["jquery-1.11.1.min.js", "prism.js", "tidy.js"]
				}
			},
			"styles": {
				"_contents": ["structure.css"]
			}
		}
	}
}

**Comment by davegomez** [comment]
Let me see if I understand... What we need is to create a JSON from a directory structure o build a directory structure from a given JSON file?

**Comment by caiovaccaro** [comment]
We need to read the directory tree in JSON format, in order to create the menu and render modules automatically.


https://github.com/hugeinc/styleguide/blob/master/styleguide/styleguide.jade#L6
https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_templates/_modules.jade#L2
https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_templates/_sidebar.jade#L23
https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_includes/modulesData.jade#L1

The last one refers to the folder styleguide/modules.

**Comment by caiovaccaro** [comment]
@davegomez is it clear now?

We need to define an architecture until the EOD today, even if we have 2-3 options to do POCs and test next week.

**Comment by davegomez** [comment]
I think it is, I will have something for later today, I'll let you know

**Comment by davegomez** [comment]
It's done. I will have it published as a small library on NPM by tomorrow so we can use at any moment. Are we looking to support from any Node.js version in particular?

**Comment by caiovaccaro** [comment]
Can we see the code first?

:D

**Comment by caiovaccaro** [comment]
@davegomez awesome!

**Comment by caiovaccaro** [comment]
So far we agree with:

- terraform
- tree-parser
