### ISSUE TITLE
Running multiple Styleguides at once

### ISSUE THREAD

**Issue by kevinchevallier** [hugeinc/styleguide#71]
Having the start.app check if the port required for the browser isn't used already.

**Comment by caiovaccaro** [comment]
Hi @kevinchevallier ! Do you want to propose a solution to that problem?

**Comment by kevinchevallier** [comment]
Will try. After a quick check, i can see that it does take place in watch.js, nothing to do with Star.app.

**Comment by davegomez** [comment]
The Styleguide server has a default config with port number included, if you want to launch more than one instance of the Styleguide you have to manually change the server port.

@caiovaccaro I think we can write a sort of check before the server starts, choose a free port and log it into the console for the user to know.

**Comment by kevinchevallier** [comment]
Exactly what i was thinking. I tried to use a tool like https://github.com/indexzero/node-portfinder but without luck so far.

**Comment by caiovaccaro** [comment]
@kevinchevallier , any improvement?

**Comment by kevinchevallier** [comment]
Solved. Just created a pull request.
