### ISSUE TITLE
Stuck on 94%

### ISSUE THREAD

**Issue by willzie** [hugeinc/styleguide#72]
When running start.app I am getting stuck on 94% when launching a server. 

I have tried running the two sudo npm commands on listed in the known issues section. But that hasn't worked. 

Log below:

/Users/jwilliams/Documents/work/RHP/RHP Documents/styleguide-master/Start.app/Contents/Resources/script: line 58: /Users/jwilliams/.bashrc: No such file or directory
Styleguide. Welcome!
PROGRESS:50
/Users/jwilliams/Documents/work/RHP/RHP Documents/styleguide-master/Start.app/Contents/Resources/script: line 28: .bashrc: No such file or directory

Checking dependencies...

npm WARN EPACKAGEJSON HugeStyleguideNodeRunner@2.0.0 No description
npm WARN EPACKAGEJSON HugeStyleguideNodeRunner@2.0.0 No repository field.
PROGRESS:80

Let's start this thing...
Starting Server on port 9241..
PROGRESS:94

**Comment by lmadenci** [comment]
I'm having the same problem on El Capitan. I changed my port to 7000 and it still only gets to 94%.
When looking in activity monitor the process exists and seems to be still trying to connect to the server.

**Comment by Nipher** [comment]
ref #34

**Comment by GraphicDesk** [comment]
Make sure that you have installed Harp

**Comment by jrdnndtsch** [comment]
Hi - I am also having a similar issue 
I am get stuck on PROGRESS: 94 (no other error message) when trying to start up the style guide. 
I have tried using the Start.app as well as the manual process.
I have also run the two sudo commands under number 3 in the known issues.
When I try to run the manual startup setting a PORT the printed message still says it is starting on port 8000 and still hangs at PROGRESS:94
I do have Harp installed. 
Any insight would be greatly appreciate :)

**Comment by caiovaccaro** [comment]
Hi!

Can you please remove all the files, download and try again? I just updated all dependencies, Node version and fixed some bugs.

If you have NodeJS installed please make sure it is the latest version.

Thank you.

**Comment by caiovaccaro** [comment]
Closing since a few versions were released after the issue created 4 months ago, fixing it.
