### ISSUE TITLE
Problem trying to compile

### ISSUE THREAD

**Issue by alanmarcos** [hugeinc/styleguide#73]
I'm having an issue trying to compile the styleguide: I have a bower_components/ folder on the root of my project with some dependencies in it (jquery, bootstrap...), but when i try to run `harp compile` on the root folder, it gives me this error: 

```
{
  "source": "Less",
  "dest": "CSS",
  "filename": "C:\\xampp\\htdocs\\ndonline\\bower_components\\bootstrap\\less\\alerts.less",
  "lineno": 10,
  "name": "NameError",
  "message": "variable @alert-padding is undefined",
  "stack": "//\n// Alerts\n// --------------------------------------------------\n\n\n// Base styles\n// -------------------------\n\n.alert {\n  padding: @alert-padding;\n  margin-bottom: @line-height-computed;\n  border: 1px solid transparent;\n  border-radius: @alert-border-radius;\n\n  // Headings for larger alerts\n  h4 {\n    margin-top: 0;\n    // Specified for the h4 to prevent conflicts of changing @headings-color\n    color: inherit;\n  }\n\n  // Provide class for links that match alerts\n  .alert-link {\n    font-weight: @alert-link-font-weight;\n  }\n\n  // Improve alignment and spacing of inner content\n  > p,\n  > ul {\n    margin-bottom: 0;\n  }\n\n  > p + p {\n    margin-top: 5px;\n  }\n}\n\n// Dismissible alerts\n//\n// Expand the right padding and account for the close button's positioning.\n\n.alert-dismissable, // The misspelled .alert-dismissable was deprecated in 3.2.0.\n.alert-dismissible {\n  padding-right: (@alert-padding + 20);\n\n  // Adjust close link position\n  .close {\n    position: relative;\n    top: -2px;\n    right: -21px;\n    color: inherit;\n  }\n}\n\n// Alternate styles\n//\n// Generate contextual modifier classes for colorizing the alert.\n\n.alert-success {\n  .alert-variant(@alert-success-bg; @alert-success-border; @alert-success-text);\n}\n\n.alert-info {\n  .alert-variant(@alert-info-bg; @alert-info-border; @alert-info-text);\n}\n\n.alert-warning {\n  .alert-variant(@alert-warning-bg; @alert-warning-border; @alert-warning-text);\n}\n\n.alert-danger {\n  .alert-variant(@alert-danger-bg; @alert-danger-border; @alert-danger-text);\n}\n"
}
```

it seems like harp is trying to compile some files from that bower_components/ folder. 
what should i do?

I'm on a Windows10 PC.

**Comment by Nipher** [comment]
Hey @alanmarcos, thanks for reporting this issue.
Could you try changing your `.bowerrc` file to change the `bower_components` to `_bower_components`?
like this:
```
{
  "directory": "_bower_components"
}
```
(harp seems to ignore files/folders beginning with underscore)

Then you would need to move the `_bower_components` folder to the compiled folder I think, for the browser could manage getting the files through http requests...

**Comment by alanmarcos** [comment]
Hey @Nipher, thanks for the amazingly fast reply!

That did worked out... kinda. Now the problem is within the `node_modules` folder:

    autoprefixer: <css input>:1:16838: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
    autoprefixer: <css input>:1:16838: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
    {
      "source": "Less",
      "dest": "CSS",
      "filename": "C:\\xampp\\htdocs\\ndonline\\node_modules\\less\\test\\browser\\less\\errors\\image-height-error.less",
      "lineno": 2,
      "name": "FileError",
      "message": "error evaluating function `image-height`: '../data/image.jpg' wasn't found. Tried - C:\\xampp\\htdocs\\ndonline\\node_modules\\less\\test\\browser\\less\\data\\image.jpg,C:\\xampp\\htdocs\\ndonline\\node_modules\\less\\test\\browser\\less\\data\\image.jpg,C:\\xampp\\data\\image.jpg,..\\data\\image.jpg",
      "stack": ".test-height{\n  height: image-height(\"../data/image.jpg\")\n}\n"
    }

But the `node_modules` folder is actually not specific to NPM, it is part of Node's core module loading system, so the name can't be changed, right?

**Comment by Nipher** [comment]
Hey @alanmarcos, it's a pleasure to help out :smile:

So... 
About `node_modules`, I've read that you really don't have any way to change the `node_modules` name.

I've found an [issue](https://github.com/sintaxi/harp/issues/393) on harp repository talking about this.

I would love to see a `.harpignore` file to list all folders that the users of harp want to ignore, but this idea is being discussed on harp github repository, and isn't implemented yet.

Anyway...
For now, the best way to solve this is keeping `node_modules` outside the folder that you want to compile...

I've this problem once, and I was using npm for front-end packages too (not only for nodejs), having css  frameworks and stuff.
If this is your case, the solution that I've think of is creating a back-end route, that serves the files of `node_modules` folder, just for development environments.

**Comment by alanmarcos** [comment]
i renamed the `node_modules` folder to `_node_modules` and ran the `harp compile` to see if it would work. instead this happens:

    {
      "source": "Jade",
      "dest": "HTML",
      "filename": "C:\\xampp\\htdocs\\ndonline\\styleguide\\structure\\_templates\\_modules.jade",
      "lineno": 6,
      "name": "TypeError",
      "message": "Cannot read property '_data' of undefined",
      "stack": "extends structure/_includes/_layout\nblock meta\n\tbase(target=\"_blank\")\nblock styles\n\tlink(href='assets/styles/structure.css', rel='stylesheet')\n\n\teach module in modulesData\n\t\t- var stylesheet = 'modules/' + module.order + '_' + module.id + '/' + module.id + '.css'\n\t\tlink(href=stylesheet, rel='stylesheet')\n\nblock content\n\t.huge-iframe-content\n\t\tinclude structure/_templates/_modules.jade\n\t\tinclude structure/_templates/_footer.jade\n\nblock scripts\n\tscript(src=\"structure/scripts/vendor/jquery-1.11.1.min.js\")\n\tscript(src=\"structure/scripts/vendor/prism.js\")\n\tscript(src=\"structure/scripts/vendor/tidy.js\")\n\tscript(src=\"structure/scripts/iframe.js\")\n\teach module in modulesData\n\t\tif module.scripts\n\t\t\teach script in module.scripts\n\t\t\t\t- var folder = 'modules/' + module.order + '_' + module.id + '/'\n\t\t\t\tscript(src='#{folder}#{script}')"
    }

is this still a harp issue?

**Comment by caiovaccaro** [comment]
Do you have any module without a _data.json file?

**Comment by caiovaccaro** [comment]
Hi!

Can you please remove all the files, download and try again? I just updated all dependencies, Node version and fixed some bugs.

If you have NodeJS installed please make sure it is the latest version.

Thank you.
