### ISSUE TITLE
Is there a script or something that can put together all the JS / SCSS compile it and uglify it for production ?

### ISSUE THREAD

**Issue by Ionut-Milas** [hugeinc/styleguide#77]

**Comment by caiovaccaro** [comment]
Hi @GraphicDesk !

Yes, I can add it in the Compile phase. Does this sounds good?
- Concatenate all CSS files and minify the bundle file
- Concatenate all JS files and uglify them

**Comment by GraphicDesk** [comment]
Perfect

**Comment by GraphicDesk** [comment]
However I saw that Harp has a lot to do with the node modules and if there is a problem it will crash...
Building the assets for production can't be done without Harp ?

**Comment by redfox05** [comment]
On the same note, is it easy for us (I'm not asking you to do it @caiovaccaro :) ) to convert from harp to using a Gulp/Grunt script to do everything harp does? The rest of our app is all Gulp.

**Comment by caiovaccaro** [comment]
We opted to leave that as an optional post-build phase. On version 3.0 we should have integrations ready for cases like this.
