### ISSUE TITLE
Compile app at "Progress: 0"

### ISSUE THREAD

**Issue by olletsoc** [hugeinc/styleguide#78]
This is what Im getting when I try to compile. I have run the Start app and the style guide is working as it should.

"Compiling Styleguide...

PROGRESS:0
Harp wasn't found, please run the Start file."

This happens when the start app is running and the style guide is active. The only option the compiler gives me is to Quit.

Any Ideas?

**Comment by caiovaccaro** [comment]
Hi! What is the OS?

**Comment by olletsoc** [comment]
Hey, Im on OS X 10.10.5

**Comment by caiovaccaro** [comment]
Hi!

Can you please remove all the files, download and try again? I just updated all dependencies, Node version and fixed some bugs.

If you have NodeJS installed please make sure it is the latest version.

Thank you.
