### ISSUE TITLE
Sass compile error visible after installation

### ISSUE THREAD

**Issue by d2s** [hugeinc/styleguide#8]
Sass compile error visible in the page header after first (and second) start of the software:

```
"Sass -> CSS (expected a variable name (e.g. $x) or ')' for the parameter list for url) /Users/d2s/Documents/github/hugeinc/styleguide/styleguide/modules/6_forms/vendor/foundation-form.scss";”
```

![screen shot 2015-07-18 at 1 58 30 pm huge style guide - firefox 39 - sass compile error](https://cloud.githubusercontent.com/assets/135053/8761595/b7c8e466-2d61-11e5-9c2b-f7304e5c9bf3.png)

![screen shot 2015-07-18 at 3 26 47 pm huge style guide - firefox 39 - sass compile error - web inspector](https://cloud.githubusercontent.com/assets/135053/8761596/deda7c2c-2d61-11e5-931f-0ae8b4568ad5.png)

*Steps to reproduce:*
- Install dependencies by starting the Start.app first time.
- See visible error on the browser.
- Restart the app to see if it would change the behavior.
- See visible error on the browser again.

I did already have Node etc. already installed via [nvm](https://github.com/creationix/nvm).

*OS:*
OS X 10.8.5

*Browser:*
Firefox 39.0

Console logs in the Start.app:

```
Styleguide. Welcome!
PROGRESS:50

Checking dependencies...

npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
npm WARN package.json Dependency 'livereload' exists in both dependencies and devDependencies, using 'livereload@^0.3.6' from dependencies
npm WARN package.json Dependency 'watch' exists in both dependencies and devDependencies, using 'watch@^0.14.0' from dependencies
PROGRESS:80

Let's start this thing...
Starting Server..
PROGRESS:94


Done! Enjoy!
PROGRESS:100
```

Mistakenly closed the app after first start, so I don’t have the install logs (from first start of the program) available anymore.

**Comment by caiovaccaro** [comment]
Done! Please download the files again or just delete the line as shown in the commit above. Let me know if that is all!

Thank you for creating the issue.

**Comment by d2s** [comment]
@caiovaccaro Thanks, works nicely after git repository sync (to the local directory).
