### ISSUE TITLE
Tag 2.0.8 was made, but Travis still shows this build as failing. Safe to use?

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#83]
Tag 2.0.8 was made, but Travis still shows this build as failing.
Is it still safe to use, or should we go back to build 111 which seems to be the last one that passed?

We are wanting to download the latest stable release and start working on it as soon as possible, so would appreciate if someone could help clarify the state of the builds.

**Comment by caiovaccaro** [comment]
Thanks @redfox05 , it is just a confusion around the internal test dependencies. I will fix that asap.

**Comment by redfox05** [comment]
Thanks for the super fast reply. Please can you close this issue once its fixed, so its easy to track.

**Comment by caiovaccaro** [comment]
Should be good to go!

**Comment by redfox05** [comment]
P.s. the download link at https://github.com/hugeinc/styleguide/archive/master.zip will that include the latest changes, or should we just use the current state of your 'master' branch?

Which is the most stable to use?

**Comment by redfox05** [comment]
I ended up using the latest pull from master.
