### ISSUE TITLE
Running 'node watch.js' not working on Windows

### ISSUE THREAD

**Issue by R0M3** [hugeinc/styleguide#84]
Using node watch.js doesn't seem to work on Windows. It seems command-exists.js is using the unix 'which' command for the child variable. Replacing this with 'where' doesn't seem to work. So it never finds harp and throws out 'Harp is not installed, please run npm install on styleguide/styleguide/structure/_node-files/'. (definitely have harp installed)

Thanks

**Comment by caiovaccaro** [comment]
Thank you, very useful to us and should be fixed soon.

**Comment by caiovaccaro** [comment]
This was related to a `command-exists` package issue which is now fixed.

https://github.com/mathisonian/command-exists/blob/master/lib/command-exists.js#L5
