### ISSUE TITLE
During preview (and on the built www) folder, error says cannot find template.css

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#85]
I keep seeing this error in console:

http://localhost:8000/styleguide/modules/8_templates/templates.css Failed to load resource: the server responded with a status of 404 (Not Found)

But searching the style-guide folders it cant find anything with reference to templates.css where would it be calling this? It says from index.hml, but cant find the original jade file generating it...

**Comment by caiovaccaro** [comment]
You might have a templates module with no CSS on it. By default the Styleguide tries to load CSS files for each module.

If you do have a templates module and there is no need for CSS, we might map those cases and don't load the CSS. That would be a minor version update.

Anyway, it is not an error but a wrong request which will not harm your application for the time being.

**Comment by redfox05** [comment]
Understood. I can close this now then if you wish.

**Comment by caiovaccaro** [comment]
I will leave it to improve it on the next minor version.
