### ISSUE TITLE
Upon deploy of www folder to webserver, page does not finish loading till half a minute later

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#86]
Each time I load the styleguide the page does not finish loading for ages! And the menu on the left does not want to seem to open. But if I load the page and wait half a minute until the status bar shows it has totally finished, THEN the menu on the left opens on click without problems.

Anyone else having this issue?

**Comment by redfox05** [comment]
FOUND THE CULPRIT!

Using the Chrome Network tab, I found that the following file ended up taking 28 seconds to attempt to load, and after the 28 seconds, it gave up and status was failed in the Chrome Network tab.

`livereload.js?snipver=1`

See screenshot below:
<img width="767" alt="screen shot 2016-06-10 at 15 41 54" src="https://cloud.githubusercontent.com/assets/7571495/15967998/01b7babc-2f22-11e6-96ef-a949e939ec76.png">

Any suggestions how to fix? I presume this is because livereload should only be there on the local dev side, and surely should not have found its way into the www folder.

**Comment by caiovaccaro** [comment]
Hi!

Which version are you using? This is an old issue that should be already fixed.

**Comment by redfox05** [comment]
It appears to be Styleguide - v.2 2016/6/10.
I only literally pulled the code after you fixed the unit tests to pass the other day.

Where is the duplicate of this, shall I continue on another ticket?

**Comment by redfox05** [comment]
Im still trying to debug this, and fix it myself, but I can't understand why livereload.js is being injected into the compiled www/index.html as livereload.js is only for the development environment correct?

I could just remove the folllowing line of code from index.html, but this would mean no live reload during dev work.

`<script src="styleguide/structure/scripts/styleguide.js"></script><script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':8374/livereload.js?snipver=1"></' + 'script>')</script>`

Any suggestions? It's very annoying to have to wait about 20-30 seconds for the loading of the script to time out, and for some reason, it stops you using any of the menus. I presume this is because jQuery is waiting for document ready before it does its click listener stuff?

**Comment by redfox05** [comment]
For the time being, my workaround is as follows:

```
	if !process.env.STYLEGUIDE_COMPILE
		script.
			if(location.host.split(':')[0]==='localhost') { document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':8374/livereload.js?snipver=1"></' + 'script>'); }
```

I know I can take out the `if !process.env.STYLEGUIDE_COMPILE` but im leaving it in incase @caiovaccaro can come back with a fix, and then its easier to add in.

**Comment by caiovaccaro** [comment]
Hi @redfox05 , thanks.

Yes if you are using the Compile.app this shouldn't happen, other wise you need to add `STYLEGUIDE_COMPILE=1` before `harp compile`.
