### ISSUE TITLE
Question: Approximate ETA of version 3.0.0

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#87]
Hi there,

Not sure if you have a forum or general questions email address, so had to post here.

In the code there are references to an upcoming version 3.0.0. Do you know when this would be finished possibly? Very rough time lines would be great if its not known. Days, weeks, months?

**Comment by caiovaccaro** [comment]
Hi! Probably a few months from now :)

**Comment by redfox05** [comment]
Awesome, thanks for the quick update. Keep up the good work :)
