### ISSUE TITLE
Enhancement: change hardcoded $magenta to $sidebarLinkHoverColor

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#88]
In `/styleguide/structure/styles/_modules/_sidebar.scss` change all references to `$magenta` to `$sidebarLinkHoverColor` otherwise when you change the value of `$sidebarLinkHoverColor` in  `/styleguide/structure/styles/_base.scss`, then the colours dont update.

**Comment by redfox05** [comment]
Also, another suggestion is to change the references in sidebar.scss for 63px to $headerHeight so that this is more centrally controlled and matches when header height is adjusted.

**Comment by caiovaccaro** [comment]
Hi @redfox05 , can you make a pull request with that? You are most welcome :)
