### ISSUE TITLE
Custom SCSS imports

### ISSUE THREAD

**Issue by creynolds86** [hugeinc/styleguide#89]
Hi,

I'm trying to import a custom Sass (SCSS) variables file which contains base brand colours.

The issue is that variables set in the `structure.scss` file are not being picked up because the modules are in an iframe and because each module has its own SCSS, how do we define variables such as colours to be used across all modules?

Importing the same variables file in to each module is not desirable.

Thanks.

**Comment by caiovaccaro** [comment]
Hi @creynolds86 ,

I totally understand the issue, and we are looking for that and other things in version 3.0. Currently the only way to do it is to separate a variables.scss file and import it in every module.

Thanks for writing.
