### ISSUE TITLE
Query: Converting harp compile to Gulp/Grunt

### ISSUE THREAD

**Issue by redfox05** [hugeinc/styleguide#90]
Hi,

I posted this question as a comment on another issue, but thought best to split it out.
How easy would it be to convert from the harp compile process to a Gulp/Grunt script?

I am happy to try do this myself, but if there are any tips or things to keep in mind, if you can post them here as a reply, that would help avoid unnecessary headache if I try to convert it.

**Comment by caiovaccaro** [comment]
Hi @redfox05 ,

We haven't planned for a full integration with grunt/gulp. I'm not sure what kind of integration you want, but you might be satisfied in attaching grunt/gulp tasks for each module in: https://github.com/hugeinc/styleguide/tree/master/styleguide/structure/_node-files
