### ISSUE TITLE
Harp is not installed, please run npm install on styleguide/styleguide/structure/_node-files/

### ISSUE THREAD

**Issue by mlaurvig** [hugeinc/styleguide#91]
Hi 

I'm getting this message during the install: "Harp is not installed, please run npm install on styleguide/styleguide/structure/_node-files/" 

Thanks

---

**Here is the full install log:**

Styleguide. Welcome!
PROGRESS:50

Checking dependencies...

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.4.2 install /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/darwin-x64-48_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

```
  export HTTP_PROXY=http://example.com:1234
```

or configure npm proxy via

```
  npm config set proxy http://example.com:8080
```

> spawn-sync@1.0.15 postinstall /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/spawn-sync
> node postinstall
> 
> node-sass@3.4.2 postinstall /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass
> node scripts/build.js

Building: /Users/mathiaslaurvig/local/bin/node /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/mathiaslaurvig/local/bin/node',
gyp verb cli   '/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:14:12)
gyp verb `which` failed     at F (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:69:19)
gyp verb `which` failed     at E (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:81:29)
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:90:16
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:14:12)
gyp verb `which` failed     at F (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:69:19)
gyp verb `which` failed     at E (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:81:29)
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/which/which.js:90:16
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.2.0
gyp verb command install [ '6.2.0' ]
gyp verb install input version string "6.2.0"
gyp verb install installing version: 6.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.2.0
gyp verb build dir attempting to create "build" dir: /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mathiaslaurvig/.node-gyp/6.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mathiaslaurvig/.node-gyp/6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/mathiaslaurvig/.node-gyp/6.2.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/mathiaslaurvig/.node-gyp/6.2.0/include/node -I/Users/mathiaslaurvig/.node-gyp/6.2.0/src -I/Users/mathiaslaurvig/.node-gyp/6.2.0/deps/uv/include -I/Users/mathiaslaurvig/.node-gyp/6.2.0/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
# include <sass/context.h>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/mathiaslaurvig/local/bin/node" "/Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/node-sass
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed
npm WARN HugeStyleguideNodeRunner@2.0.8 No description
npm WARN HugeStyleguideNodeRunner@2.0.8 No repository field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/mathiaslaurvig/local/bin/node" "/Users/mathiaslaurvig/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mathiaslaurvig/Downloads/styleguide-master/styleguide/structure/_node-files/npm-debug.log
PROGRESS:80

Let's start this thing...
Harp is not installed, please run npm install on styleguide/styleguide/structure/_node-files/
PROGRESS:100

**Comment by sosheepster** [comment]
It might be related to this issue on Harp: https://github.com/sintaxi/harp/issues/564

I had Node 6 installed, and had to change the Harp version to make it work.

**Comment by fyllepo** [comment]
We're also experiencing this issue, but haven't had much look with Node 6.2 yet and getting harp to work, did you find any solution to this one @mlaurvig

**Comment by mlaurvig** [comment]
Nope :-(

**Comment by caiovaccaro** [comment]
@mlaurvig @sosheepster @fyllepo , have you had any luck with the latest version of Harp and Node?

**Comment by ekfuhrmann** [comment]
I'm having the same issue. Has anyone found a solution to this yet?

**Comment by caiovaccaro** [comment]
Hi @ekfuhrmann ,

Are you using windows, mac or linux? Have you tried to install harp manually?

**Comment by wirelessed** [comment]
I managed to force harp to the latest version by changing package.json, and then used yarn to install instead of npm. it seems to work after that!

**Comment by ideacco** [comment]
I'm having the same issue. Has anyone found a solution to this yet?

**Comment by programiro** [comment]
U have to install install harp@next with npm version 4 lts…

**Comment by caiovaccaro** [comment]
Updating the dependencies version solved for me. Just pushed to a separate branch. If you can please test, downloading a zip from this link: https://github.com/hugeinc/styleguide/tree/hotfix/dependencies-version

**Comment by miukimiu** [comment]
My solution was to use a lower version of node. I changed it with nvm to the version **5.1.0**. I also installed the latest version of harp: `npm install -g harp@next`
