### ISSUE TITLE
Livereload port is fixed

### ISSUE THREAD

**Issue by namirsab** [hugeinc/styleguide#92]
Hi everybody,
Is there anyway to change the livereload port?
It's not possible to have 2 instances of HUGE running in the same server because the livereload port is fixed to 8375.

I know this issue is not following the styleguide but I didn't know where to ask.
So, if there is a better place to ask questions like this, please tell me and remove this issue.

thanks a lot!

**Comment by caiovaccaro** [comment]
Hi @namirsab !

Right now the only way to do it is manually.

You have to change the port in two places:

1. https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_node-files/modules/livereloader.js
2. https://github.com/hugeinc/styleguide/blob/master/index.jade
